### ISSUE TITLE
Error: unable to resolve actions/conda-skeleton-publish@v1

### ISSUE THREAD

**Issue by ubaldot** [teamholtz/conda-skeleton-publish#4]
I am trying to use this action but I get ` Error: Unable to resolve action `actions/conda-skeleton-publish@v1`, repository not found`
Any hints on how to fix it?

**Comment by lucaswells** [comment]
Hi @ubaldot, you will need to specify the user/org in the YAML `uses` key for your workflow definition:

```
uses: silvxlabs/conda-skeleton-publish@v2
```

The example in the README only works for local tests. I'm closing this issue; feel free to reopen it if you continue to experience issues.

**Comment by ubaldot** [comment]
Ah ok! Now it works! It is a bit confusing that sometimes you just use actions some other times user (not a critique on your tool which looks great!). 
But now I have another issue though: 

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqbeqwoasconda_skeleton_dymoval-0.5.2.tar.gz/dymoval-0.5.2/setup.py'`

My project does not have any `setup.py` as it uses the new `pyproject.toml` file.
Shall I open a dedicated issue (even if that seems more a conda related problem. It seems they haven't updated their build system for projects that only have `pyproject.toml files)`?  

Also, I have 

```
with:
    pypi_package: dymoval
    python_version: [3](https://github.com/VolvoGroup/dymoval/actions/runs/3421083499/jobs/5696740008#step:3:3).10
    upload_channel: conda-forge
    access_token: ***
    stable: true
    package_version: latest
    build_channels: conda-forge
    platforms: win-6[4](https://github.com/VolvoGroup/dymoval/actions/runs/3421083499/jobs/5696740008#step:3:4) osx-[6](https://github.com/VolvoGroup/dymoval/actions/runs/3421083499/jobs/5696740008#step:3:6)4 osx-arm64 linux-64 linux-aarch64
    wait: false

```

but I got 

```
=======================================
Creating build recipe from PyPI package
=======================================
/opt/conda/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!

```

i.e. I asked for `Python 3.10` but it seems it is using `Python 3.9`
